## Application Programming Interface
Graphical User Interface (GUI)

- Python Libraries!
- Web APIs : REST APIs
- Representational State Transfer

### REST APIs
- Protocall https://
- Web url www.google.com, api.open-meteo.com
- Endpoint /v1/forecast
- Query start ?
- key=value
- Parameters separated by &
<br>
https://api.open-meteo.com/v1/forecast?latitue=52.52&longitude=13.41&hourly=temp_2m
<br><br>
https = hypertext transfer protocol (secure)

In [1]:
import json
import requests

In [2]:
url = "https://api.open-meteo.com/v1/forecast?latitude=53.2724&longitude=-9.051&current=temperature_2m,rain&hourly=temperature_2m,rain"

In [3]:
res = requests.get(url)

In [4]:
res # 200 = Good

In [5]:
res.text

'{"latitude":53.27,"longitude":-9.05,"generationtime_ms":0.09202957153320312,"utc_offset_seconds":0,"timezone":"GMT","timezone_abbreviation":"GMT","elevation":10.0,"current_units":{"time":"iso8601","interval":"seconds","temperature_2m":"°C","rain":"mm"},"current":{"time":"2023-11-27T12:15","interval":900,"temperature_2m":9.6,"rain":0.00},"hourly_units":{"time":"iso8601","temperature_2m":"°C","rain":"mm"},"hourly":{"time":["2023-11-27T00:00","2023-11-27T01:00","2023-11-27T02:00","2023-11-27T03:00","2023-11-27T04:00","2023-11-27T05:00","2023-11-27T06:00","2023-11-27T07:00","2023-11-27T08:00","2023-11-27T09:00","2023-11-27T10:00","2023-11-27T11:00","2023-11-27T12:00","2023-11-27T13:00","2023-11-27T14:00","2023-11-27T15:00","2023-11-27T16:00","2023-11-27T17:00","2023-11-27T18:00","2023-11-27T19:00","2023-11-27T20:00","2023-11-27T21:00","2023-11-27T22:00","2023-11-27T23:00","2023-11-28T00:00","2023-11-28T01:00","2023-11-28T02:00","2023-11-28T03:00","2023-11-28T04:00","2023-11-28T05:00","2023-11-28T06:00","2023-11-28T07:00","2023-11-28T08:00","2023-11-28T09:00","2023-11-28T10:00","2023-11-28T11:00","2023-11-28T12:00","2023-11-28T13:00","2023-11-28T14:00","2023-11-28T15:00","2023-11-28T16:00","2023-11-28T17:00","2023-11-28T18:00","2023-11-28T19:00","2023-11-28T20:00","2023-11-28T21:00","2023-11-28T22:00","2023-11-28T23:00","2023-11-29T00:00","2023-11-29T01:00","2023-11-29T02:00","2023-11-29T03:00","2023-11-29T04:00","2023-11-29T05:00","2023-11-29T06:00","2023-11-29T07:00","2023-11-29T08:00","2023-11-29T09:00","2023-11-29T10:00","2023-11-29T11:00","2023-11-29T12:00","2023-11-29T13:00","2023-11-29T14:00","2023-11-29T15:00","2023-11-29T16:00","2023-11-29T17:00","2023-11-29T18:00","2023-11-29T19:00","2023-11-29T20:00","2023-11-29T21:00","2023-11-29T22:00","2023-11-29T23:00","2023-11-30T00:00","2023-11-30T01:00","2023-11-30T02:00","2023-11-30T03:00","2023-11-30T04:00","2023-11-30T05:00","2023-11-30T06:00","2023-11-30T07:00","2023-11-30T08:00","2023-11-30T09:00","2023-11-30T10:00","2023-11-30T11:00","2023-11-30T12:00","2023-11-30T13:00","2023-11-30T14:00","2023-11-30T15:00","2023-11-30T16:00","2023-11-30T17:00","2023-11-30T18:00","2023-11-30T19:00","2023-11-30T20:00","2023-11-30T21:00","2023-11-30T22:00","2023-11-30T23:00","2023-12-01T00:00","2023-12-01T01:00","2023-12-01T02:00","2023-12-01T03:00","2023-12-01T04:00","2023-12-01T05:00","2023-12-01T06:00","2023-12-01T07:00","2023-12-01T08:00","2023-12-01T09:00","2023-12-01T10:00","2023-12-01T11:00","2023-12-01T12:00","2023-12-01T13:00","2023-12-01T14:00","2023-12-01T15:00","2023-12-01T16:00","2023-12-01T17:00","2023-12-01T18:00","2023-12-01T19:00","2023-12-01T20:00","2023-12-01T21:00","2023-12-01T22:00","2023-12-01T23:00","2023-12-02T00:00","2023-12-02T01:00","2023-12-02T02:00","2023-12-02T03:00","2023-12-02T04:00","2023-12-02T05:00","2023-12-02T06:00","2023-12-02T07:00","2023-12-02T08:00","2023-12-02T09:00","2023-12-02T10:00","2023-12-02T11:00","2023-12-02T12:00","2023-12-02T13:00","2023-12-02T14:00","2023-12-02T15:00","2023-12-02T16:00","2023-12-02T17:00","2023-12-02T18:00","2023-12-02T19:00","2023-12-02T20:00","2023-12-02T21:00","2023-12-02T22:00","2023-12-02T23:00","2023-12-03T00:00","2023-12-03T01:00","2023-12-03T02:00","2023-12-03T03:00","2023-12-03T04:00","2023-12-03T05:00","2023-12-03T06:00","2023-12-03T07:00","2023-12-03T08:00","2023-12-03T09:00","2023-12-03T10:00","2023-12-03T11:00","2023-12-03T12:00","2023-12-03T13:00","2023-12-03T14:00","2023-12-03T15:00","2023-12-03T16:00","2023-12-03T17:00","2023-12-03T18:00","2023-12-03T19:00","2023-12-03T20:00","2023-12-03T21:00","2023-12-03T22:00","2023-12-03T23:00"],"temperature_2m":[9.9,9.8,9.7,9.7,9.6,8.9,9.2,9.7,9.7,10.0,9.7,9.2,9.5,9.4,9.8,10.1,9.1,8.0,7.4,6.5,6.0,5.9,5.6,5.6,5.5,4.8,4.2,4.4,3.1,4.3,4.4,5.6,5.3,6.6,7.6,8.2,8.6,9.0,9.2,9.1,8.5,8.2,7.5,5.0,5.0,4.7,4.2,4.0,3.6,3.0,2.6,2.7,2.5,2.4,2.3,2.4,2.1,2.0,1.6,1.9,2.2,2.4,3.0,3.6,3.7,3.6,3.3,3.1,2.7,2.3,2.1,2.1,2.0,2.0,2.0,2.3,2.2,2.1,1.8,2.0,1.7,1.6,2.0,2.9,3.8,4.3,4.4,4.4,4.1,3.5,3.0,2.5,2.3,2.4,2.9,3.1,3.6,3.7,3.8,4.0,4.0,4.2,4.3,-0.4,-0.5,-0.3,0.3,1.2,2.0,2.8,3.6,3.9,3.3,2.3,1.4,0.9,0.6,0.4,0.2,0.1,-0.1,-0.2,-0.3,-0.5,-0.7,-0.8,-1.0,2.2,1.3,0.9,1.4,2.4,3.2,3.7,4.0,3.8,2.8,1.4,0.3,-0.1,-0.3,-0.3,-0.1,0.1,0.4,0.6,0.8,1.0,1.2,1.5,1.8,2.1,2.6,3.0,3.4,3.8,4.2,4.7,5.2,5.6,5.7,5.6,5.6,5.6,5.5,5.5,5.4,5.3],"rain":[0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.30,0.30,0.30,0.50,0.50,0.50,0.90,0.90,0.90,0.50,0.50,0.50,0.10,0.10]}}'

In [6]:
res.text[:10]

'{"latitude'

In [7]:
data = json.loads(res.text)

In [8]:
data["latitude"]

53.27

In [9]:
type(data)

dict

In [10]:
data["current"]

{'time': '2023-11-27T12:15',
 'interval': 900,
 'temperature_2m': 9.6,
 'rain': 0.0}

In [11]:
data["current"]["temperature_2m"]

9.6

In [12]:
json_data = json.dumps(data)

In [13]:
json_data

'{"latitude": 53.27, "longitude": -9.05, "generationtime_ms": 0.09202957153320312, "utc_offset_seconds": 0, "timezone": "GMT", "timezone_abbreviation": "GMT", "elevation": 10.0, "current_units": {"time": "iso8601", "interval": "seconds", "temperature_2m": "\\u00b0C", "rain": "mm"}, "current": {"time": "2023-11-27T12:15", "interval": 900, "temperature_2m": 9.6, "rain": 0.0}, "hourly_units": {"time": "iso8601", "temperature_2m": "\\u00b0C", "rain": "mm"}, "hourly": {"time": ["2023-11-27T00:00", "2023-11-27T01:00", "2023-11-27T02:00", "2023-11-27T03:00", "2023-11-27T04:00", "2023-11-27T05:00", "2023-11-27T06:00", "2023-11-27T07:00", "2023-11-27T08:00", "2023-11-27T09:00", "2023-11-27T10:00", "2023-11-27T11:00", "2023-11-27T12:00", "2023-11-27T13:00", "2023-11-27T14:00", "2023-11-27T15:00", "2023-11-27T16:00", "2023-11-27T17:00", "2023-11-27T18:00", "2023-11-27T19:00", "2023-11-27T20:00", "2023-11-27T21:00", "2023-11-27T22:00", "2023-11-27T23:00", "2023-11-28T00:00", "2023-11-28T01:00", "2023-11-28T02:00", "2023-11-28T03:00", "2023-11-28T04:00", "2023-11-28T05:00", "2023-11-28T06:00", "2023-11-28T07:00", "2023-11-28T08:00", "2023-11-28T09:00", "2023-11-28T10:00", "2023-11-28T11:00", "2023-11-28T12:00", "2023-11-28T13:00", "2023-11-28T14:00", "2023-11-28T15:00", "2023-11-28T16:00", "2023-11-28T17:00", "2023-11-28T18:00", "2023-11-28T19:00", "2023-11-28T20:00", "2023-11-28T21:00", "2023-11-28T22:00", "2023-11-28T23:00", "2023-11-29T00:00", "2023-11-29T01:00", "2023-11-29T02:00", "2023-11-29T03:00", "2023-11-29T04:00", "2023-11-29T05:00", "2023-11-29T06:00", "2023-11-29T07:00", "2023-11-29T08:00", "2023-11-29T09:00", "2023-11-29T10:00", "2023-11-29T11:00", "2023-11-29T12:00", "2023-11-29T13:00", "2023-11-29T14:00", "2023-11-29T15:00", "2023-11-29T16:00", "2023-11-29T17:00", "2023-11-29T18:00", "2023-11-29T19:00", "2023-11-29T20:00", "2023-11-29T21:00", "2023-11-29T22:00", "2023-11-29T23:00", "2023-11-30T00:00", "2023-11-30T01:00", "2023-11-30T02:00", "2023-11-30T03:00", "2023-11-30T04:00", "2023-11-30T05:00", "2023-11-30T06:00", "2023-11-30T07:00", "2023-11-30T08:00", "2023-11-30T09:00", "2023-11-30T10:00", "2023-11-30T11:00", "2023-11-30T12:00", "2023-11-30T13:00", "2023-11-30T14:00", "2023-11-30T15:00", "2023-11-30T16:00", "2023-11-30T17:00", "2023-11-30T18:00", "2023-11-30T19:00", "2023-11-30T20:00", "2023-11-30T21:00", "2023-11-30T22:00", "2023-11-30T23:00", "2023-12-01T00:00", "2023-12-01T01:00", "2023-12-01T02:00", "2023-12-01T03:00", "2023-12-01T04:00", "2023-12-01T05:00", "2023-12-01T06:00", "2023-12-01T07:00", "2023-12-01T08:00", "2023-12-01T09:00", "2023-12-01T10:00", "2023-12-01T11:00", "2023-12-01T12:00", "2023-12-01T13:00", "2023-12-01T14:00", "2023-12-01T15:00", "2023-12-01T16:00", "2023-12-01T17:00", "2023-12-01T18:00", "2023-12-01T19:00", "2023-12-01T20:00", "2023-12-01T21:00", "2023-12-01T22:00", "2023-12-01T23:00", "2023-12-02T00:00", "2023-12-02T01:00", "2023-12-02T02:00", "2023-12-02T03:00", "2023-12-02T04:00", "2023-12-02T05:00", "2023-12-02T06:00", "2023-12-02T07:00", "2023-12-02T08:00", "2023-12-02T09:00", "2023-12-02T10:00", "2023-12-02T11:00", "2023-12-02T12:00", "2023-12-02T13:00", "2023-12-02T14:00", "2023-12-02T15:00", "2023-12-02T16:00", "2023-12-02T17:00", "2023-12-02T18:00", "2023-12-02T19:00", "2023-12-02T20:00", "2023-12-02T21:00", "2023-12-02T22:00", "2023-12-02T23:00", "2023-12-03T00:00", "2023-12-03T01:00", "2023-12-03T02:00", "2023-12-03T03:00", "2023-12-03T04:00", "2023-12-03T05:00", "2023-12-03T06:00", "2023-12-03T07:00", "2023-12-03T08:00", "2023-12-03T09:00", "2023-12-03T10:00", "2023-12-03T11:00", "2023-12-03T12:00", "2023-12-03T13:00", "2023-12-03T14:00", "2023-12-03T15:00", "2023-12-03T16:00", "2023-12-03T17:00", "2023-12-03T18:00", "2023-12-03T19:00", "2023-12-03T20:00", "2023-12-03T21:00", "2023-12-03T22:00", "2023-12-03T23:00"], "temperature_2m": [9.9, 9.8, 9.7, 9.7, 9.6, 8.9, 9.2, 9.7, 9.7, 10.0, 9.7, 9.2, 9.5, 9.4, 9.8, 10.1, 9.1, 8.0, 7.4, 6.5, 6.0, 5.9, 5.6, 5.6, 5.5, 4.8, 4.2, 4.4, 3.1, 4.3, 4.4, 5.6, 5.3, 6.6, 7.6, 8.2, 8.6, 9.0, 9.2, 9.1, 8.5, 8.2, 7.5, 5.0, 5.0, 4.7, 4.2, 4.0, 3.6, 3.0, 2.6, 2.7, 2.5, 2.4, 2.3, 2.4, 2.1, 2.0, 1.6, 1.9, 2.2, 2.4, 3.0, 3.6, 3.7, 3.6, 3.3, 3.1, 2.7, 2.3, 2.1, 2.1, 2.0, 2.0, 2.0, 2.3, 2.2, 2.1, 1.8, 2.0, 1.7, 1.6, 2.0, 2.9, 3.8, 4.3, 4.4, 4.4, 4.1, 3.5, 3.0, 2.5, 2.3, 2.4, 2.9, 3.1, 3.6, 3.7, 3.8, 4.0, 4.0, 4.2, 4.3, -0.4, -0.5, -0.3, 0.3, 1.2, 2.0, 2.8, 3.6, 3.9, 3.3, 2.3, 1.4, 0.9, 0.6, 0.4, 0.2, 0.1, -0.1, -0.2, -0.3, -0.5, -0.7, -0.8, -1.0, 2.2, 1.3, 0.9, 1.4, 2.4, 3.2, 3.7, 4.0, 3.8, 2.8, 1.4, 0.3, -0.1, -0.3, -0.3, -0.1, 0.1, 0.4, 0.6, 0.8, 1.0, 1.2, 1.5, 1.8, 2.1, 2.6, 3.0, 3.4, 3.8, 4.2, 4.7, 5.2, 5.6, 5.7, 5.6, 5.6, 5.6, 5.5, 5.5, 5.4, 5.3], "rain": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.3, 0.3, 0.5, 0.5, 0.5, 0.9, 0.9, 0.9, 0.5, 0.5, 0.5, 0.1, 0.1]}}'

In [14]:
data['hourly']['time'][0]

'2023-11-27T00:00'

In [15]:
data['hourly']['temperature_2m'][0]

9.9

In [16]:
data['hourly'].keys()

dict_keys(['time', 'temperature_2m', 'rain'])

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame({
    "Time" : data['hourly']['time'],
    "Tempurature" : data['hourly']['temperature_2m'],
    "Rain" : data['hourly']['rain']
})

In [19]:
df.head()

               Time  Tempurature  Rain
0  2023-11-27T00:00          9.9   0.0
1  2023-11-27T01:00          9.8   0.0
2  2023-11-27T02:00          9.7   0.0
3  2023-11-27T03:00          9.7   0.0
4  2023-11-27T04:00          9.6   0.0

In [20]:
df2 = pd.DataFrame(data['hourly'])

In [21]:
df2.head()

               time  temperature_2m  rain
0  2023-11-27T00:00             9.9   0.0
1  2023-11-27T01:00             9.8   0.0
2  2023-11-27T02:00             9.7   0.0
3  2023-11-27T03:00             9.7   0.0
4  2023-11-27T04:00             9.6   0.0

In [22]:
df3 = pd.DataFrame(data)

In [23]:
df3.shape

(4, 11)

In [24]:
df.shape

(168, 3)

In [26]:
data.keys()

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'current_units', 'current', 'hourly_units', 'hourly'])

In [27]:
data["current"].keys()

dict_keys(['time', 'interval', 'temperature_2m', 'rain'])

In [28]:
data["current"]["temperature_2m"]

9.6